version: "3"
services:
  loki:
    image: grafana/loki:1.4.1
    container_name: gl_loki
    expose:
      - 3100
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
    command: -config.file=/etc/loki/loki.yml
    networks:
      - gl

  promtail:
    image: grafana/promtail:1.4.1
    container_name: gl_promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - ../test-log.log:/var/log/test-log.log:ro
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - gl

  prometheus:
    image: prom/prometheus:latest
    container_name: gl_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gl

  # myapp:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile
  #   container_name: gl_myapp
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - gl

  myapp:
    image: deploy_myapp
    container_name: gl_myapp
    ports:
      - "8080:8080"
    networks:
      - gl

  grafana:
    image: grafana/grafana:master
    container_name: gl_grafana
    ports:
      - "3000:3000"
    networks:
      - gl

networks:
  gl:

